const SYMBOL_WEIGHTS = {
  BASE: {
    WILD: 2, DRAGON_RED: 6, DRAGON_BLACK: 6,
    BAMBOO: 10, CIRCLE: 12, CHARACTER: 14,
    WIND_N: 16, WIND_S: 18, FLOWER: 20, SEASON: 22,
    GOLDEN: 5, SCATTER_RED: 3, SCATTER_BLACK: 2, SCATTER_GOLDEN: 1
  },
  FREE_SPIN: {
    WILD: 5, DRAGON_RED: 8, DRAGON_BLACK: 8,
    BAMBOO: 10, CIRCLE: 12, CHARACTER: 14,
    WIND_N: 16, WIND_S: 18, FLOWER: 20, SEASON: 22,
    GOLDEN: 8, SCATTER_RED: 1, SCATTER_BLACK: 1, SCATTER_GOLDEN: 0
  }
};
